//============================================================================
// Auto-Zoom Screensaver
//
// Cycles through canonical Mandelbrot POIs (count + data come from
// rtl/poi_generated.vh — generated by tools/poi_encode.py).
// Starts on reset, Z key toggles. Target/palette order is shuffled once per
// core reset using Fisher-Yates with LFSR-driven rejection sampling.
//
// Snap mode (M key / X button via snap_next): jumps directly to the next
// POI's canonical zoom depth (DEFAULT_STEP >>> target_zoom_int) and holds
// in S_HOLD until snap_next pulses again, or auto-zoom is disabled.
//============================================================================

`include "poi_generated.vh"

module auto_zoom #(
    parameter WIDTH     = 64,
    parameter FRAC_BITS = 56
)(
    input  wire                    clk,
    input  wire                    rst_n,
    input  wire                    enable,
    input  wire                    skip_next,
    input  wire                    snap_next,       // M key / X button: snap to next POI canonical view
    input  wire                    frame_done,
    input  wire                    vblank,
    input  wire [32:0]             entropy_seed,
    // Attract Mode (from fractal_osd):
    input  wire                    attract_zoom_in_enable,
    input  wire                    attract_zoom_out_enable,
    input  wire [15:0]             attract_wait_vblanks,
    // Dwell qualifier: dwell vblanks only count while high.  Gallery
    // mode holds it low until the 1080p frame is fully committed to
    // DDR3 and the fade/flip settled — "Wait on POI" then measures
    // pure DISPLAY time, not render time.  Tied high otherwise.
    input  wire                    dwell_gate,
    // Zoom pacing during S_ZOOM_IN:
    //   1'b0 = Cinematic (default — slow first ~60 steps + slow last few zoom levels)
    //   1'b1 = Constant  (step_delta = step/512 every frame, no pacing)
    input  wire                    zoom_pacing_mode,
    // Zoom speed (auto-zoom only; manual zoom uses its own rate):
    //   2'd0 = Normal     (step >>> 9 = step/512, current default)
    //   2'd1 = Slow       (step >>> 10 = step/1024, half speed)
    //   2'd2 = Fast       (step >>> 8  = step/256,  2x speed)
    //   2'd3 = Very Fast  (step >>> 7  = step/128,  4x speed)
    input  wire [1:0]              zoom_speed_sel,
    // Attract Randomizer (OSD O[52], default On): per-POI random draw of
    // color-cycling speed/direction and auto-zoom speed.  Pools chosen
    // for screensaver taste: CC speed 300 baud..33.6k (no Teletype, no
    // ISDN+), direction forward/reverse only (no ping-pong), zoom speed
    // Normal/Fast/Very Fast (no Slow).
    input  wire                    randomize_enable,

    // BRAM framebuffer sampling (held inactive in deterministic zoom mode)
    input  wire [12:0]             fb_rd_data,
    output wire [17:0]             fb_rd_addr,
    output wire                    fb_sampling,

    output reg  signed [WIDTH-1:0] center_x,
    output reg  signed [WIDTH-1:0] center_y,
    output reg  signed [WIDTH-1:0] step,
    output reg                     active,
    output reg                     view_changed,
    output reg  [6:0]              palette_idx,
    output wire [`POI_IDX_BITS-1:0] target_idx_out,
    output reg  [11:0]              target_max_iter,
    // Per-POI random draws (valid whenever randomize_enable; consumers
    // in fractal_top additionally gate on auto_zoom active)
    output reg  [3:0]               rnd_cycle_speed,
    output reg  [1:0]               rnd_cycle_direction,
    output reg  [1:0]               rnd_zoom_speed
);

localparam signed [WIDTH-1:0] DEFAULT_STEP = 64'sh0003333333333333;
localparam signed [WIDTH-1:0] MIN_STEP     = 64'sh0000000000000010;
localparam N_TARGETS  = `POI_N_TARGETS;
localparam N_PALETTES = 90;
localparam IDX_BITS   = `POI_IDX_BITS;
localparam PAL_BITS   = 7;
localparam [IDX_BITS-1:0] TARGET_LAST_IDX  = `POI_LAST_IDX;
localparam [PAL_BITS-1:0] PALETTE_LAST_IDX = N_PALETTES - 1;

// State encoding (4 bits to comfortably hold 8 states)
localparam [3:0] S_IDLE      = 4'd0,
                 S_ZOOM_IN   = 4'd1,
                 S_ZOOM_OUT  = 4'd2,
                 S_NEXT      = 4'd3,
                 S_SHUFFLE   = 4'd4,
                 S_LOAD      = 4'd5,
                 S_HOLD      = 4'd6,   // verification-mode static hold
                 S_SNAP_LOAD = 4'd7;   // advance playlist + snap to target zoom

reg [3:0]  state;
reg [IDX_BITS-1:0] target_idx;
reg [15:0] zoom_steps;
reg [15:0] dwell_count;
// vblank rising-edge detector — drives wall-clock dwell so a "10 second"
// wait stays 10 seconds regardless of render fps (was frame_done-based,
// which stretched dwell to many minutes on sub-1fps deep zoom POIs).
reg        vblank_prev;
wire       vblank_rise = vblank & ~vblank_prev;
reg [15:0] free_counter;
reg [15:0] target_lfsr;
reg [15:0] palette_lfsr;
reg [IDX_BITS-1:0] target_playlist_pos;
reg [PAL_BITS-1:0] palette_playlist_pos;
reg                shuffle_phase;
reg [IDX_BITS-1:0] shuffle_idx;
reg                zoom_out_final_pending;
reg                seed_pending;

// ---- Playlist memories (ALM diet, 2026-07-08) ----
// Synchronous-read 90-entry arrays so Quartus infers MLABs instead of
// two 90:1 muxes + 1,260 flops (~1.4k ALUTs).  One read + one write
// port each; the Fisher-Yates swap is sequenced over 5 cycles (see
// S_SHUFFLE subphases) and the POI advance over 4 (S_NEXT/S_SNAP_LOAD)
// — both are reset-time / once-per-POI paths where cycles are free.
// NOTE: contents are NOT reset (that would block RAM inference); the
// identity fill happens in the SSUB_FILL shuffle subphase instead.
reg [IDX_BITS-1:0] target_playlist  [0:N_TARGETS-1];
reg [PAL_BITS-1:0] palette_playlist [0:N_PALETTES-1];
reg [IDX_BITS-1:0] tp_raddr, tp_waddr, tp_wdata;
reg [IDX_BITS-1:0] tp_rdata;
reg                tp_we;
reg [PAL_BITS-1:0] pp_raddr, pp_waddr, pp_wdata;
reg [PAL_BITS-1:0] pp_rdata;
reg                pp_we;

always @(posedge clk) begin
    if (tp_we) target_playlist[tp_waddr] <= tp_wdata;
    tp_rdata <= target_playlist[tp_raddr];
end
always @(posedge clk) begin
    if (pp_we) palette_playlist[pp_waddr] <= pp_wdata;
    pp_rdata <= palette_playlist[pp_raddr];
end

// Shuffle / advance sequencing state
localparam [2:0] SSUB_FILL  = 3'd0,  // identity-fill both memories
                 SSUB_DRAW  = 3'd1,  // advance LFSRs, accept/reject j
                 SSUB_RD_HI = 3'd2,  // mem[i] read in flight
                 SSUB_RD_LO = 3'd3,  // latch hi, mem[j] read in flight
                 SSUB_WR_LO = 3'd4,  // write mem[i] <= lo
                 SSUB_WR_HI = 3'd5,  // write mem[j] <= hi, advance i
                 SSUB_FIN_A = 3'd6,  // (reserved — unused)
                 SSUB_FIN_B = 3'd7;  // (reserved — unused)
reg [2:0]          ssub;
reg [IDX_BITS-1:0] shuffle_j_r;      // accepted swap partner
reg [IDX_BITS-1:0] shuffle_hi_r;     // mem[i] held across the swap
reg [IDX_BITS-1:0] fill_idx;
reg [1:0]          adv_ph;           // S_NEXT / S_SNAP_LOAD subphase

// ---- POI data (rom_cx, rom_cy, target_max_zoom_x10, target_zoom_int) ----
reg signed [WIDTH-1:0] rom_cx, rom_cy;
always @(*) begin
    case (target_idx)
        `POI_ROM_CASES
        default: begin rom_cx = 64'shFFD0000000000000; rom_cy = 64'sh0000000000000000; end
    endcase
end

reg [9:0] target_max_zoom_x10;
always @(*) begin
    case (target_idx)
        `POI_ZOOM_CASES
        default: target_max_zoom_x10 = 10'd80;
    endcase
end

reg [4:0] target_zoom_int;
always @(*) begin
    case (target_idx)
        `POI_ZOOM_INT_CASES
        default: target_zoom_int = 5'd8;
    endcase
end

always @(*) begin
    case (target_idx)
        `POI_ITER_CASES
        default: target_max_iter = 12'd1024;
    endcase
end

// ---- Zoom rate (per-frame step adjustment) ----
// Speed selector picks the shift amount applied to `step` to derive
// step_shift.  Bigger shift = smaller delta = slower zoom.
wire [1:0] effective_zoom_speed = randomize_enable ? rnd_zoom_speed : zoom_speed_sel;
reg [3:0] zoom_speed_shift;
always @(*) begin
    case (effective_zoom_speed)
        2'd1: zoom_speed_shift = 4'd10;  // Slow
        2'd2: zoom_speed_shift = 4'd8;   // Fast
        2'd3: zoom_speed_shift = 4'd7;   // Very Fast
        default: zoom_speed_shift = 4'd9; // Normal (default)
    endcase
end
wire signed [WIDTH-1:0] step_shift = step >>> zoom_speed_shift;
wire signed [WIDTH-1:0] step_delta_base = (step_shift == {WIDTH{1'b0}}) ? {{(WIDTH-1){1'b0}}, 1'b1} : step_shift;

// Zoom pacing — modifies step_delta on a per-frame basis based on
// where we are in the zoom-in trajectory.  See zoom_pacing_mode.
// `zoom_remaining` and `is_early_phase` are below the zoom_level_x10
// computation (lines 200-ish); the wire declarations there reference
// values that exist by the time S_ZOOM_IN consumes step_delta.

// ---- Snap target step: DEFAULT_STEP >>> target_zoom_int ----
wire signed [WIDTH-1:0] snap_step = DEFAULT_STEP >>> target_zoom_int;

// ---- LFSR + shuffle helpers ----
function [15:0] lfsr_advance;
    input [15:0] state_in;
    begin
        lfsr_advance = {state_in[14:0], state_in[15] ^ state_in[13] ^ state_in[12] ^ state_in[10]};
    end
endfunction

// 4 candidates × 7 bits = 28 bits (fits in 32-bit rand_state).
// Per-attempt accept probability for max_idx=72: 57%; for max_idx=46: 37%.
// Failing all 4: ~3% target / ~16% palette → fallback (TARGET_LAST_IDX) is rare.
function [IDX_BITS-1:0] next_shuffle_candidate;
    input [31:0]            rand_state;
    input [IDX_BITS-1:0]    max_idx;
    reg   [IDX_BITS-1:0]    c0, c1, c2, c3;
    begin
        c0 = rand_state[IDX_BITS-1:0];
        c1 = rand_state[2*IDX_BITS-1:IDX_BITS];
        c2 = rand_state[3*IDX_BITS-1:2*IDX_BITS];
        c3 = rand_state[4*IDX_BITS-1:3*IDX_BITS];

        if (c0 <= max_idx)        next_shuffle_candidate = c0;
        else if (c1 <= max_idx)   next_shuffle_candidate = c1;
        else if (c2 <= max_idx)   next_shuffle_candidate = c2;
        else if (c3 <= max_idx)   next_shuffle_candidate = c3;
        else                      next_shuffle_candidate = {IDX_BITS{1'b1}};
    end
endfunction

// ---- Step → zoom level, computed SERIALLY (ALM diet, 2026-07-08) ----
// The old combinational form needed a 16-nibble priority tree plus a
// 64-bit barrel shifter (~1k ALUTs) to normalize `step` every cycle —
// but the result is only consumed at frame cadence.  Instead: whenever
// `step` changes, shift a copy left one bit per clock until normalized
// (<=64 cycles, i.e. <=1.3 us), then derive exponent and fraction from
// the normalized value.  Consumers keep using the previous registered
// value while a recompute is in flight; the freshness margin to the
// next frame_done/vblank consumer is >100x the recompute time.  The
// brief stale window can at most add one dwell vblank tick or pace one
// frame with the previous delta — invisible.
reg signed [WIDTH-1:0] zstep_prev;
reg [63:0] znorm;
reg [5:0]  znorm_sh;                // shift count so far
reg        zbusy;
reg [5:0]  zoom_exp_r;
reg [3:0]  zoom_frac_nibble_r;
reg        zoom_ge_default_r;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        zstep_prev         <= {WIDTH{1'b0}};
        znorm              <= 64'd0;
        znorm_sh           <= 6'd0;
        zbusy              <= 1'b0;
        zoom_exp_r         <= 6'd0;
        zoom_frac_nibble_r <= 4'd15;
        zoom_ge_default_r  <= 1'b1;
    end else begin
        zstep_prev <= step;
        if (step != zstep_prev) begin
            znorm    <= step[63:0];
            znorm_sh <= 6'd0;
            zbusy    <= 1'b1;
        end else if (zbusy) begin
            if (znorm[63] || (znorm_sh == 6'd63)) begin
                zbusy              <= 1'b0;
                zoom_ge_default_r  <= (step >= DEFAULT_STEP);
                zoom_frac_nibble_r <= znorm[62:59];
                // step_msb = 63 - znorm_sh; zoom_exp = 49 - step_msb
                zoom_exp_r         <= znorm_sh - 6'd14;
            end else begin
                znorm    <= {znorm[62:0], 1'b0};
                znorm_sh <= znorm_sh + 6'd1;
            end
        end
    end
end

reg [3:0] zoom_frac_tenth_az;
always @(*) begin
    if (zoom_ge_default_r)                  zoom_frac_tenth_az = 4'd0;
    else if (zoom_frac_nibble_r >= 4'd14) zoom_frac_tenth_az = 4'd0;
    else if (zoom_frac_nibble_r >= 4'd13) zoom_frac_tenth_az = 4'd1;
    else if (zoom_frac_nibble_r >= 4'd11) zoom_frac_tenth_az = 4'd2;
    else if (zoom_frac_nibble_r >= 4'd9)  zoom_frac_tenth_az = 4'd3;
    else if (zoom_frac_nibble_r >= 4'd7)  zoom_frac_tenth_az = 4'd4;
    else if (zoom_frac_nibble_r >= 4'd6)  zoom_frac_tenth_az = 4'd5;
    else if (zoom_frac_nibble_r >= 4'd4)  zoom_frac_tenth_az = 4'd6;
    else if (zoom_frac_nibble_r >= 4'd3)  zoom_frac_tenth_az = 4'd7;
    else if (zoom_frac_nibble_r >= 4'd1)  zoom_frac_tenth_az = 4'd8;
    else                                  zoom_frac_tenth_az = 4'd9;
end

wire [5:0] zoom_exp = zoom_ge_default_r ? 6'd0 : zoom_exp_r;
wire [9:0] zoom_level_x10 = zoom_exp * 4'd10 + {6'd0, zoom_frac_tenth_az};

// ---- Zoom pacing (Cinematic by default) ----
// Slow the first ~60 zoom steps (anticipation) and the last ~5 zoom-x10
// levels (landing).  Slowing factor is /4 in both phases.  Constant mode
// just uses step_delta_base unchanged.  Floor to 1 so zoom never stalls.
wire [9:0] zoom_remaining_x10 = (zoom_level_x10 < target_max_zoom_x10)
                                ? (target_max_zoom_x10 - zoom_level_x10)
                                : 10'd0;
wire is_early_phase = (zoom_steps          < 16'd60);
wire is_late_phase  = (zoom_remaining_x10  < 10'd5);

wire signed [WIDTH-1:0] step_delta_paced_raw =
    zoom_pacing_mode ? step_delta_base                                 // Constant
                     : ((is_early_phase || is_late_phase)              // Cinematic
                        ? (step_delta_base >>> 2)
                        : step_delta_base);

wire signed [WIDTH-1:0] step_delta = (step_delta_paced_raw == {WIDTH{1'b0}})
                                     ? {{(WIDTH-1){1'b0}}, 1'b1}
                                     : step_delta_paced_raw;

// ---- LFSR-driven shuffle bookkeeping ----
reg enable_prev;
wire enable_rise = enable & ~enable_prev;
wire unused_ok = &{1'b0, vblank, fb_rd_data[12:0]};
wire [15:0] target_seed_mix  = entropy_seed[15:0] ^ entropy_seed[31:16] ^ {15'd0, entropy_seed[32]};
wire [15:0] palette_seed_mix = {entropy_seed[23:8]} ^ {entropy_seed[7:0], entropy_seed[31:24]} ^ {15'd0, entropy_seed[32]};
wire [15:0] next_target_lfsr   = lfsr_advance(target_lfsr ^ free_counter);
wire [15:0] next_target_lfsr2  = lfsr_advance(next_target_lfsr ^ {free_counter[7:0], free_counter[15:8]});
wire [15:0] next_palette_lfsr  = lfsr_advance(palette_lfsr ^ {free_counter[7:0], free_counter[15:8]});
wire [15:0] next_palette_lfsr2 = lfsr_advance(next_palette_lfsr ^ free_counter);
wire [31:0] target_rand_pool   = {next_target_lfsr2, next_target_lfsr};
wire [31:0] palette_rand_pool  = {next_palette_lfsr2, next_palette_lfsr};
wire [IDX_BITS-1:0] shuffle_target_j  = next_shuffle_candidate(target_rand_pool, shuffle_idx);
wire [IDX_BITS-1:0] shuffle_palette_j = next_shuffle_candidate(palette_rand_pool, shuffle_idx);
wire target_shuffle_accept  = (shuffle_target_j  <= shuffle_idx);
wire palette_shuffle_accept = (shuffle_palette_j <= shuffle_idx);
// (Playlist entry values are read through the synchronous memory ports —
// see the S_SHUFFLE subphase machine; the old combinational hi/lo/first
// helper wires were the 90:1 muxes this diet removes.)

assign fb_rd_addr = 18'd0;
assign fb_sampling = 1'b0;
assign target_idx_out = target_idx;

wire dwell_done = (dwell_count >= (attract_wait_vblanks - 16'd1));

// ---- Attract Randomizer draw ----
// Dedicated free-running LFSR, advanced EVERY clock: the thousands of
// cycles between POI advances fully decorrelate consecutive draws.
// (A first attempt derived draws as lfsr_advance(static ^ free_counter)
// once per draw — near-linear in the counter, so regular attract pacing
// produced strongly correlated speeds/directions.  Caught by the TB.)
reg [15:0] rnd_lfsr;
// CC speed pool (OSD sel values): 300(2), 1200(3), 2400(4), 9600(0),
// 14.4k(5), 28.8k(6) — top tier 33.6k excluded per user spec, 28.8k
// double-weighted; the leftover 3-bit slot goes to the neutral 9600.
reg [3:0] rnd_speed_map;
always @(*) begin
    case (rnd_lfsr[2:0])
        3'd0: rnd_speed_map = 4'd2;   // 300 baud
        3'd1: rnd_speed_map = 4'd3;   // 1200
        3'd2: rnd_speed_map = 4'd4;   // 2400
        3'd3: rnd_speed_map = 4'd0;   // 9600
        3'd4: rnd_speed_map = 4'd5;   // 14.4k
        3'd5: rnd_speed_map = 4'd6;   // 28.8k
        3'd6: rnd_speed_map = 4'd6;   // 28.8k (double weight)
        default: rnd_speed_map = 4'd0; // 9600
    endcase
end
// Zoom speed pool: Fast(2) and Very Fast(3) only, Fast double-weighted —
// 4-bit threshold gives 11/16 : 5/16 (~2.2:1, closest binary fit to 2:1).
reg [1:0] rnd_zoom_map;
always @(*) begin
    rnd_zoom_map = (rnd_lfsr[9:6] < 4'd11) ? 2'd2 : 2'd3;
end

// ---- Width helpers (used in many state-machine transitions) ----
localparam [IDX_BITS-1:0] IDX_ZERO = {IDX_BITS{1'b0}};
localparam [IDX_BITS-1:0] IDX_ONE  = {{(IDX_BITS-1){1'b0}}, 1'b1};
localparam [PAL_BITS-1:0] PAL_ZERO = {PAL_BITS{1'b0}};
localparam [PAL_BITS-1:0] PAL_ONE  = {{(PAL_BITS-1){1'b0}}, 1'b1};

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        state <= S_SHUFFLE; active <= 1'b1; view_changed <= 1'b1;
        center_x <= 64'shFFD0000000000000; // -0.75
        center_y <= 64'sh0000000000000000;
        step <= DEFAULT_STEP; target_idx <= IDX_ZERO;
        palette_idx <= PAL_ZERO; enable_prev <= 1'b0;
        zoom_steps <= 16'd0;
        dwell_count <= 16'd0;
        vblank_prev <= 1'b0;
        free_counter <= 16'h0001;
        target_lfsr <= 16'hA5C3;
        palette_lfsr <= 16'h5E31;
        target_playlist_pos <= IDX_ONE;
        palette_playlist_pos <= PAL_ONE;
        shuffle_phase <= 1'b0;
        shuffle_idx <= TARGET_LAST_IDX;
        zoom_out_final_pending <= 1'b0;
        seed_pending <= 1'b1;
        rnd_cycle_speed     <= 4'd0;   // 9600 (default)
        rnd_cycle_direction <= 2'd0;   // forward
        rnd_zoom_speed      <= 2'd0;   // normal
        rnd_lfsr            <= 16'h7A21;
        // Playlist memory contents deliberately NOT reset (MLAB inference);
        // SSUB_FILL writes the identity permutation before shuffling.
        ssub         <= SSUB_FILL;
        fill_idx     <= IDX_ZERO;
        adv_ph       <= 2'd0;
        shuffle_j_r  <= IDX_ZERO;
        shuffle_hi_r <= IDX_ZERO;
        tp_raddr <= IDX_ZERO; tp_waddr <= IDX_ZERO; tp_wdata <= IDX_ZERO; tp_we <= 1'b0;
        pp_raddr <= PAL_ZERO; pp_waddr <= PAL_ZERO; pp_wdata <= PAL_ZERO; pp_we <= 1'b0;
    end else begin
        if (unused_ok) begin end
        free_counter <= free_counter + 16'd1;
        enable_prev <= enable; view_changed <= 1'b0;
        vblank_prev <= vblank;
        tp_we <= 1'b0;
        pp_we <= 1'b0;
        rnd_lfsr <= lfsr_advance(rnd_lfsr);
        if (seed_pending) begin
            target_lfsr <= 16'hA5C3 ^ target_seed_mix;
            palette_lfsr <= 16'h5E31 ^ palette_seed_mix;
            rnd_lfsr <= 16'h7A21 ^ target_seed_mix ^ {palette_seed_mix[7:0], palette_seed_mix[15:8]};
            seed_pending <= 1'b0;
        end else case (state)
        S_SHUFFLE: begin
            // Fisher-Yates over the two MLAB playlists, one swap per 5
            // cycles (draw, read i, read j, write i, write j).  Runs
            // once per reset (~1.2k cycles = 25 us) — latency-free zone.
            active <= 1'b0;
            case (ssub)
            SSUB_FILL: begin
                // Identity permutation into both memories, one entry/clk.
                tp_we <= 1'b1; tp_waddr <= fill_idx; tp_wdata <= fill_idx;
                pp_we <= 1'b1; pp_waddr <= fill_idx[PAL_BITS-1:0]; pp_wdata <= fill_idx[PAL_BITS-1:0];
                if (fill_idx == TARGET_LAST_IDX) begin
                    shuffle_phase <= 1'b0;
                    shuffle_idx   <= TARGET_LAST_IDX;
                    ssub          <= SSUB_DRAW;
                end else begin
                    fill_idx <= fill_idx + IDX_ONE;
                end
            end
            SSUB_DRAW: begin
                if (!shuffle_phase) begin
                    target_lfsr <= next_target_lfsr2;
                    if (target_shuffle_accept) begin
                        shuffle_j_r <= shuffle_target_j;
                        tp_raddr    <= shuffle_idx;
                        ssub        <= SSUB_RD_HI;
                    end
                end else begin
                    palette_lfsr <= next_palette_lfsr2;
                    if (palette_shuffle_accept) begin
                        shuffle_j_r <= shuffle_palette_j;
                        pp_raddr    <= shuffle_idx[PAL_BITS-1:0];
                        ssub        <= SSUB_RD_HI;
                    end
                end
            end
            SSUB_RD_HI: begin
                // mem[i] read in flight; queue the mem[j] read.
                if (!shuffle_phase) tp_raddr <= shuffle_j_r;
                else                pp_raddr <= shuffle_j_r[PAL_BITS-1:0];
                ssub <= SSUB_RD_LO;
            end
            SSUB_RD_LO: begin
                // rdata now holds mem[i]; mem[j] read in flight.
                shuffle_hi_r <= shuffle_phase
                                ? {{(IDX_BITS-PAL_BITS){1'b0}}, pp_rdata}
                                : tp_rdata;
                ssub <= SSUB_WR_LO;
            end
            SSUB_WR_LO: begin
                // rdata now holds mem[j]; write it to [i].
                if (!shuffle_phase) begin
                    tp_we <= 1'b1; tp_waddr <= shuffle_idx; tp_wdata <= tp_rdata;
                end else begin
                    pp_we <= 1'b1; pp_waddr <= shuffle_idx[PAL_BITS-1:0]; pp_wdata <= pp_rdata;
                end
                ssub <= SSUB_WR_HI;
            end
            SSUB_WR_HI: begin
                // Write held mem[i] to [j]; advance / flip phase / finish.
                if (!shuffle_phase) begin
                    tp_we <= 1'b1; tp_waddr <= shuffle_j_r; tp_wdata <= shuffle_hi_r;
                    if (shuffle_idx == IDX_ONE) begin
                        shuffle_phase <= 1'b1;
                        shuffle_idx   <= {{(IDX_BITS-PAL_BITS){1'b0}}, PALETTE_LAST_IDX};
                    end else begin
                        shuffle_idx <= shuffle_idx - IDX_ONE;
                    end
                end else begin
                    pp_we <= 1'b1; pp_waddr <= shuffle_j_r[PAL_BITS-1:0]; pp_wdata <= shuffle_hi_r[PAL_BITS-1:0];
                    if (shuffle_idx == IDX_ONE) begin
                        // Done: start playback from playlist position 0 via
                        // the S_NEXT advance machinery (replaces the old
                        // combinational playlist[0] read + S_LOAD entry).
                        target_playlist_pos  <= IDX_ZERO;
                        palette_playlist_pos <= PAL_ZERO;
                        adv_ph <= 2'd0;
                        state  <= S_NEXT;
                    end else begin
                        shuffle_idx <= shuffle_idx - IDX_ONE;
                    end
                end
                ssub <= SSUB_DRAW;
            end
            default: ssub <= SSUB_DRAW;
            endcase
        end
        // S_LOAD is no longer entered (the shuffle exits through the
        // S_NEXT advance machinery since the MLAB restructure); kept as
        // a safe landing state for the 4-bit encoding.
        S_LOAD: begin
            if (!enable) begin
                active <= 1'b0;
                state <= S_IDLE;
            end else if (snap_next) begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= snap_step;
                view_changed <= 1'b1;
                active <= 1'b1;
                state <= S_HOLD;
            end else begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                // Attract Mode: skip the gradual zoom-in animation when
                // disabled — jump straight to the POI's canonical zoom.
                // S_ZOOM_IN then sees zoom_level_x10 >= target_max_zoom_x10
                // immediately and falls into the dwell branch.
                step <= attract_zoom_in_enable ? DEFAULT_STEP : snap_step;
                zoom_steps <= 16'd0;
                dwell_count <= 16'd0;
                active <= 1'b1;
                view_changed <= 1'b1;
                adv_ph <= 2'd0;
                zoom_out_final_pending <= 1'b0;
                state <= S_ZOOM_IN;
            end
        end
        S_IDLE: begin
            active <= 1'b0;
            if (enable_rise) begin
                center_x<=rom_cx; center_y<=rom_cy;
                step<= attract_zoom_in_enable ? DEFAULT_STEP : snap_step;
                zoom_steps<=16'd0; dwell_count<=16'd0;
                active<=1'b1; view_changed<=1'b1; zoom_out_final_pending<=1'b0; state<=S_ZOOM_IN;
            end else if (snap_next && enable) begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= snap_step;
                view_changed <= 1'b1;
                active <= 1'b1;
                state <= S_HOLD;
            end
        end
        S_ZOOM_IN: begin
            if (!enable) begin active<=1'b0; state<=S_IDLE; dwell_count<=16'd0; zoom_out_final_pending<=1'b0; end
            else if (snap_next) begin
                // First snap: stay on current target_idx, just snap step depth
                step <= snap_step;
                view_changed <= 1'b1;
                state <= S_HOLD;
            end
            else if (skip_next) begin dwell_count<=16'd0; adv_ph<=2'd0; state<=S_NEXT; end
            else begin
                // Dwell counts vblanks (wall-clock); zoom-in steps still
                // gated on frame_done so each step shows a finished frame.
                // When zoom-in is disabled, ALWAYS dwell — never zoom-step
                // further (S_LOAD/S_NEXT seeded us at snap_step, but that
                // can land slightly shallower than target_max_zoom_x10
                // due to the *10 vs *integer-zoom mismatch, which would
                // otherwise trigger spurious zoom-in animation).
                if (!attract_zoom_in_enable
                    || (step <= MIN_STEP)
                    || (zoom_level_x10 >= target_max_zoom_x10)) begin
                    if (dwell_done) begin
                        dwell_count <= 16'd0;
                        zoom_out_final_pending <= 1'b0;
                        // Reset adv_ph so S_NEXT actually advances to
                        // the next POI/palette (S_ZOOM_OUT does this too,
                        // but when we skip directly to S_NEXT we'd loop on
                        // the same POI without it).
                        adv_ph <= 2'd0;
                        // Skip the zoom-out animation when disabled
                        state <= attract_zoom_out_enable ? S_ZOOM_OUT : S_NEXT;
                    end else if (vblank_rise && dwell_gate) begin
                        dwell_count <= dwell_count + 16'd1;
                    end
                end else if (frame_done) begin
                    dwell_count <= 16'd0;
                    step <= step - step_delta;
                    zoom_steps <= zoom_steps + 16'd1;
                    view_changed <= 1'b1;
                end
            end
        end
        S_ZOOM_OUT: begin
            if (!enable) begin active<=1'b0; state<=S_IDLE; dwell_count<=16'd0; zoom_out_final_pending<=1'b0; end
            else if (snap_next) begin
                step <= snap_step;
                view_changed <= 1'b1;
                state <= S_HOLD;
            end
            else if (skip_next) begin dwell_count<=16'd0; adv_ph<=2'd0; zoom_out_final_pending<=1'b0; state<=S_NEXT; end
            else if (frame_done) begin
                if (zoom_out_final_pending) begin
                    zoom_out_final_pending <= 1'b0;
                    adv_ph <= 2'd0;
                    dwell_count <= 16'd0;
                    state <= S_NEXT;
                end else if (step >= DEFAULT_STEP) begin
                    // Exit condition is now step-based (not zoom_steps),
                    // so zoom-out animates correctly even when entered
                    // from a snap (zoom-in disabled → zoom_steps stayed 0).
                    step <= DEFAULT_STEP;
                    view_changed <= 1'b1;
                    zoom_out_final_pending <= 1'b1;
                end else begin
                    step <= step + step_delta;
                    if (zoom_steps != 16'd0)
                        zoom_steps <= zoom_steps - 16'd1;
                    view_changed <= 1'b1;
                end
            end
        end
        S_NEXT: begin
            // 4-phase advance (synchronous playlist reads):
            //   0: queue reads at the current positions
            //   1: reads in flight
            //   2: latch new target/palette idx, advance positions
            //   3: rom_cx/snap_step now reflect the new idx — load view
            if (!enable) begin active<=1'b0; state<=S_IDLE; dwell_count<=16'd0; end
            else case (adv_ph)
            2'd0: begin
                tp_raddr <= target_playlist_pos;
                pp_raddr <= palette_playlist_pos;
                adv_ph   <= 2'd1;
            end
            2'd1: adv_ph <= 2'd2;
            2'd2: begin
                target_idx  <= tp_rdata;
                palette_idx <= pp_rdata;
                target_playlist_pos  <= (target_playlist_pos  == TARGET_LAST_IDX)  ? IDX_ZERO : (target_playlist_pos  + IDX_ONE);
                palette_playlist_pos <= (palette_playlist_pos == PALETTE_LAST_IDX) ? PAL_ZERO : (palette_playlist_pos + PAL_ONE);
                // Attract Randomizer: fresh draws land with the new POI.
                rnd_cycle_speed     <= rnd_speed_map;
                rnd_cycle_direction <= {1'b0, rnd_lfsr[3]};
                rnd_zoom_speed      <= rnd_zoom_map;
                adv_ph <= 2'd3;
            end
            default: begin
                center_x<=rom_cx; center_y<=rom_cy;
                step <= attract_zoom_in_enable ? DEFAULT_STEP : snap_step;
                zoom_steps<=16'd0; dwell_count<=16'd0;
                view_changed<=1'b1; active<=1'b1; state<=S_ZOOM_IN;
            end
            endcase
        end
        S_HOLD: begin
            // Static hold at canonical zoom. Exits on:
            //   - !enable: drop to S_IDLE (Z toggled off)
            //   - snap_next: advance playlist + re-snap (S_SNAP_LOAD)
            //   - skip_next: advance + start a normal zoom-in (S_NEXT)
            if (!enable) begin
                active <= 1'b0;
                state <= S_IDLE;
            end else if (snap_next) begin
                adv_ph <= 2'd0;
                state <= S_SNAP_LOAD;
            end else if (skip_next) begin
                dwell_count<=16'd0; adv_ph<=2'd0;
                zoom_out_final_pending<=1'b0;
                state<=S_NEXT;
            end
        end
        S_SNAP_LOAD: begin
            // Same 4-phase advance as S_NEXT, landing in S_HOLD at the
            // POI's canonical snap depth.
            if (!enable) begin
                active <= 1'b0;
                state <= S_IDLE;
            end else case (adv_ph)
            2'd0: begin
                tp_raddr <= target_playlist_pos;
                pp_raddr <= palette_playlist_pos;
                adv_ph   <= 2'd1;
            end
            2'd1: adv_ph <= 2'd2;
            2'd2: begin
                target_idx  <= tp_rdata;
                palette_idx <= pp_rdata;
                target_playlist_pos  <= (target_playlist_pos  == TARGET_LAST_IDX)  ? IDX_ZERO : (target_playlist_pos  + IDX_ONE);
                palette_playlist_pos <= (palette_playlist_pos == PALETTE_LAST_IDX) ? PAL_ZERO : (palette_playlist_pos + PAL_ONE);
                // Attract Randomizer: fresh draws land with the new POI.
                rnd_cycle_speed     <= rnd_speed_map;
                rnd_cycle_direction <= {1'b0, rnd_lfsr[3]};
                rnd_zoom_speed      <= rnd_zoom_map;
                adv_ph <= 2'd3;
            end
            default: begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= snap_step;
                view_changed <= 1'b1;
                active <= 1'b1;
                state <= S_HOLD;
            end
            endcase
        end
        default: state <= S_IDLE;
        endcase
    end
end

endmodule
