//============================================================================
// Auto-Zoom Screensaver
//
// Cycles through canonical Mandelbrot POIs (count + data come from
// rtl/poi_generated.vh — generated by tools/poi_encode.py).
// Starts on reset, Z key toggles. Target/palette order is shuffled once per
// core reset using Fisher-Yates with LFSR-driven rejection sampling.
//
// Snap mode (M key / X button via snap_next): jumps directly to the next
// POI's canonical zoom depth (DEFAULT_STEP >>> target_zoom_int) and holds
// in S_HOLD until snap_next pulses again, or auto-zoom is disabled.
//============================================================================

`include "poi_generated.vh"

module auto_zoom #(
    parameter WIDTH     = 64,
    parameter FRAC_BITS = 56,
    parameter [9:0] MAX_DWELL_FRAMES = 10'd600  // 10s at 60fps
)(
    input  wire                    clk,
    input  wire                    rst_n,
    input  wire                    enable,
    input  wire                    skip_next,
    input  wire                    snap_next,       // M key / X button: snap to next POI canonical view
    input  wire                    frame_done,
    input  wire                    vblank,
    input  wire [32:0]             entropy_seed,

    // BRAM framebuffer sampling (held inactive in deterministic zoom mode)
    input  wire [12:0]             fb_rd_data,
    output wire [17:0]             fb_rd_addr,
    output wire                    fb_sampling,

    output reg  signed [WIDTH-1:0] center_x,
    output reg  signed [WIDTH-1:0] center_y,
    output reg  signed [WIDTH-1:0] step,
    output reg                     active,
    output reg                     view_changed,
    output reg  [6:0]              palette_idx,
    output wire [`POI_IDX_BITS-1:0] target_idx_out
);

localparam signed [WIDTH-1:0] DEFAULT_STEP = 64'sh0003333333333333;
localparam signed [WIDTH-1:0] MIN_STEP     = 64'sh0000000000000010;
localparam N_TARGETS  = `POI_N_TARGETS;
localparam N_PALETTES = 90;
localparam IDX_BITS   = `POI_IDX_BITS;
localparam PAL_BITS   = 7;
localparam [IDX_BITS-1:0] TARGET_LAST_IDX  = `POI_LAST_IDX;
localparam [PAL_BITS-1:0] PALETTE_LAST_IDX = N_PALETTES - 1;

// State encoding (4 bits to comfortably hold 8 states)
localparam [3:0] S_IDLE      = 4'd0,
                 S_ZOOM_IN   = 4'd1,
                 S_ZOOM_OUT  = 4'd2,
                 S_NEXT      = 4'd3,
                 S_SHUFFLE   = 4'd4,
                 S_LOAD      = 4'd5,
                 S_HOLD      = 4'd6,   // verification-mode static hold
                 S_SNAP_LOAD = 4'd7;   // advance playlist + snap to target zoom

reg [3:0]  state;
reg [IDX_BITS-1:0] target_idx;
reg [15:0] zoom_steps;
reg [9:0]  dwell_count;
reg [15:0] free_counter;
reg [15:0] target_lfsr;
reg [15:0] palette_lfsr;
reg [IDX_BITS-1:0] target_playlist  [0:N_TARGETS-1];
reg [PAL_BITS-1:0] palette_playlist [0:N_PALETTES-1];
reg [IDX_BITS-1:0] target_playlist_pos;
reg [PAL_BITS-1:0] palette_playlist_pos;
reg                shuffle_phase;
reg [IDX_BITS-1:0] shuffle_idx;
reg                zoom_out_final_pending;
reg                seed_pending;
integer            i;

// ---- POI data (rom_cx, rom_cy, target_max_zoom_x10, target_zoom_int) ----
reg signed [WIDTH-1:0] rom_cx, rom_cy;
always @(*) begin
    case (target_idx)
        `POI_ROM_CASES
        default: begin rom_cx = 64'shFFD0000000000000; rom_cy = 64'sh0000000000000000; end
    endcase
end

reg [9:0] target_max_zoom_x10;
always @(*) begin
    case (target_idx)
        `POI_ZOOM_CASES
        default: target_max_zoom_x10 = 10'd80;
    endcase
end

reg [4:0] target_zoom_int;
always @(*) begin
    case (target_idx)
        `POI_ZOOM_INT_CASES
        default: target_zoom_int = 5'd8;
    endcase
end

// ---- Zoom rate (per-frame step adjustment) ----
wire signed [WIDTH-1:0] step_shift = step >>> 9;
wire signed [WIDTH-1:0] step_delta = (step_shift == {WIDTH{1'b0}}) ? {{(WIDTH-1){1'b0}}, 1'b1} : step_shift;

// ---- Snap target step: DEFAULT_STEP >>> target_zoom_int ----
wire signed [WIDTH-1:0] snap_step = DEFAULT_STEP >>> target_zoom_int;

// ---- LFSR + shuffle helpers ----
function [15:0] lfsr_advance;
    input [15:0] state_in;
    begin
        lfsr_advance = {state_in[14:0], state_in[15] ^ state_in[13] ^ state_in[12] ^ state_in[10]};
    end
endfunction

// 4 candidates × 7 bits = 28 bits (fits in 32-bit rand_state).
// Per-attempt accept probability for max_idx=72: 57%; for max_idx=46: 37%.
// Failing all 4: ~3% target / ~16% palette → fallback (TARGET_LAST_IDX) is rare.
function [IDX_BITS-1:0] next_shuffle_candidate;
    input [31:0]            rand_state;
    input [IDX_BITS-1:0]    max_idx;
    reg   [IDX_BITS-1:0]    c0, c1, c2, c3;
    begin
        c0 = rand_state[IDX_BITS-1:0];
        c1 = rand_state[2*IDX_BITS-1:IDX_BITS];
        c2 = rand_state[3*IDX_BITS-1:2*IDX_BITS];
        c3 = rand_state[4*IDX_BITS-1:3*IDX_BITS];

        if (c0 <= max_idx)        next_shuffle_candidate = c0;
        else if (c1 <= max_idx)   next_shuffle_candidate = c1;
        else if (c2 <= max_idx)   next_shuffle_candidate = c2;
        else if (c3 <= max_idx)   next_shuffle_candidate = c3;
        else                      next_shuffle_candidate = {IDX_BITS{1'b1}};
    end
endfunction

function [1:0] nibble_msb;
    input [3:0] nibble;
    begin
        casez (nibble)
            4'b1???: nibble_msb = 2'd3;
            4'b01??: nibble_msb = 2'd2;
            4'b001?: nibble_msb = 2'd1;
            default: nibble_msb = 2'd0;
        endcase
    end
endfunction

// ---- Step → zoom level (for comparing against target_max_zoom_x10) ----
reg [5:0] step_msb;
always @(*) begin
    if (step[63:60] != 4'd0)      step_msb = 6'd60 + {4'd0, nibble_msb(step[63:60])};
    else if (step[59:56] != 4'd0) step_msb = 6'd56 + {4'd0, nibble_msb(step[59:56])};
    else if (step[55:52] != 4'd0) step_msb = 6'd52 + {4'd0, nibble_msb(step[55:52])};
    else if (step[51:48] != 4'd0) step_msb = 6'd48 + {4'd0, nibble_msb(step[51:48])};
    else if (step[47:44] != 4'd0) step_msb = 6'd44 + {4'd0, nibble_msb(step[47:44])};
    else if (step[43:40] != 4'd0) step_msb = 6'd40 + {4'd0, nibble_msb(step[43:40])};
    else if (step[39:36] != 4'd0) step_msb = 6'd36 + {4'd0, nibble_msb(step[39:36])};
    else if (step[35:32] != 4'd0) step_msb = 6'd32 + {4'd0, nibble_msb(step[35:32])};
    else if (step[31:28] != 4'd0) step_msb = 6'd28 + {4'd0, nibble_msb(step[31:28])};
    else if (step[27:24] != 4'd0) step_msb = 6'd24 + {4'd0, nibble_msb(step[27:24])};
    else if (step[23:20] != 4'd0) step_msb = 6'd20 + {4'd0, nibble_msb(step[23:20])};
    else if (step[19:16] != 4'd0) step_msb = 6'd16 + {4'd0, nibble_msb(step[19:16])};
    else if (step[15:12] != 4'd0) step_msb = 6'd12 + {4'd0, nibble_msb(step[15:12])};
    else if (step[11:8]  != 4'd0) step_msb = 6'd8  + {4'd0, nibble_msb(step[11:8])};
    else if (step[7:4]   != 4'd0) step_msb = 6'd4  + {4'd0, nibble_msb(step[7:4])};
    else                          step_msb = {4'd0, nibble_msb(step[3:0])};
end

wire [5:0] zoom_exp = (step >= DEFAULT_STEP) ? 6'd0 : (6'd49 - step_msb);

wire [63:0] step_norm_az = step << (6'd63 - step_msb);
wire [3:0]  frac_nibble_az = step_norm_az[62:59];
reg  [3:0]  zoom_frac_tenth_az;
always @(*) begin
    if (step >= DEFAULT_STEP)         zoom_frac_tenth_az = 4'd0;
    else if (frac_nibble_az >= 4'd14) zoom_frac_tenth_az = 4'd0;
    else if (frac_nibble_az >= 4'd13) zoom_frac_tenth_az = 4'd1;
    else if (frac_nibble_az >= 4'd11) zoom_frac_tenth_az = 4'd2;
    else if (frac_nibble_az >= 4'd9)  zoom_frac_tenth_az = 4'd3;
    else if (frac_nibble_az >= 4'd7)  zoom_frac_tenth_az = 4'd4;
    else if (frac_nibble_az >= 4'd6)  zoom_frac_tenth_az = 4'd5;
    else if (frac_nibble_az >= 4'd4)  zoom_frac_tenth_az = 4'd6;
    else if (frac_nibble_az >= 4'd3)  zoom_frac_tenth_az = 4'd7;
    else if (frac_nibble_az >= 4'd1)  zoom_frac_tenth_az = 4'd8;
    else                              zoom_frac_tenth_az = 4'd9;
end

wire [9:0] zoom_level_x10 = zoom_exp * 4'd10 + {6'd0, zoom_frac_tenth_az};

// ---- LFSR-driven shuffle bookkeeping ----
reg enable_prev;
wire enable_rise = enable & ~enable_prev;
reg next_loaded;
wire unused_ok = &{1'b0, vblank, fb_rd_data[12:0]};
wire [15:0] target_seed_mix  = entropy_seed[15:0] ^ entropy_seed[31:16] ^ {15'd0, entropy_seed[32]};
wire [15:0] palette_seed_mix = {entropy_seed[23:8]} ^ {entropy_seed[7:0], entropy_seed[31:24]} ^ {15'd0, entropy_seed[32]};
wire [15:0] next_target_lfsr   = lfsr_advance(target_lfsr ^ free_counter);
wire [15:0] next_target_lfsr2  = lfsr_advance(next_target_lfsr ^ {free_counter[7:0], free_counter[15:8]});
wire [15:0] next_palette_lfsr  = lfsr_advance(palette_lfsr ^ {free_counter[7:0], free_counter[15:8]});
wire [15:0] next_palette_lfsr2 = lfsr_advance(next_palette_lfsr ^ free_counter);
wire [31:0] target_rand_pool   = {next_target_lfsr2, next_target_lfsr};
wire [31:0] palette_rand_pool  = {next_palette_lfsr2, next_palette_lfsr};
wire [IDX_BITS-1:0] shuffle_target_j  = next_shuffle_candidate(target_rand_pool, shuffle_idx);
wire [IDX_BITS-1:0] shuffle_palette_j = next_shuffle_candidate(palette_rand_pool, shuffle_idx);
wire target_shuffle_accept  = (shuffle_target_j  <= shuffle_idx);
wire palette_shuffle_accept = (shuffle_palette_j <= shuffle_idx);
wire [IDX_BITS-1:0] target_hi_val = target_playlist[shuffle_idx];
wire [IDX_BITS-1:0] target_lo_val = target_shuffle_accept ? target_playlist[shuffle_target_j] : {IDX_BITS{1'b0}};
wire [PAL_BITS-1:0] palette_hi_val = palette_playlist[shuffle_idx[PAL_BITS-1:0]];
wire [PAL_BITS-1:0] palette_lo_val = palette_shuffle_accept ? palette_playlist[shuffle_palette_j[PAL_BITS-1:0]] : {PAL_BITS{1'b0}};
wire [PAL_BITS-1:0] palette_first_val = (shuffle_idx == {{(IDX_BITS-1){1'b0}}, 1'b1} && shuffle_palette_j == {IDX_BITS{1'b0}}) ? palette_hi_val : palette_playlist[0];

assign fb_rd_addr = 18'd0;
assign fb_sampling = 1'b0;
assign target_idx_out = target_idx;

wire dwell_done = (dwell_count >= (MAX_DWELL_FRAMES - 10'd1));

// ---- Width helpers (used in many state-machine transitions) ----
localparam [IDX_BITS-1:0] IDX_ZERO = {IDX_BITS{1'b0}};
localparam [IDX_BITS-1:0] IDX_ONE  = {{(IDX_BITS-1){1'b0}}, 1'b1};
localparam [PAL_BITS-1:0] PAL_ZERO = {PAL_BITS{1'b0}};
localparam [PAL_BITS-1:0] PAL_ONE  = {{(PAL_BITS-1){1'b0}}, 1'b1};

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        state <= S_SHUFFLE; active <= 1'b1; view_changed <= 1'b1;
        center_x <= 64'shFFD0000000000000; // -0.75
        center_y <= 64'sh0000000000000000;
        step <= DEFAULT_STEP; target_idx <= IDX_ZERO;
        palette_idx <= PAL_ZERO; enable_prev <= 1'b0; next_loaded <= 1'b0;
        zoom_steps <= 16'd0;
        dwell_count <= 10'd0;
        free_counter <= 16'h0001;
        target_lfsr <= 16'hA5C3;
        palette_lfsr <= 16'h5E31;
        target_playlist_pos <= IDX_ONE;
        palette_playlist_pos <= PAL_ONE;
        shuffle_phase <= 1'b0;
        shuffle_idx <= TARGET_LAST_IDX;
        zoom_out_final_pending <= 1'b0;
        seed_pending <= 1'b1;
        for (i = 0; i < N_TARGETS; i = i + 1)
            target_playlist[i] <= i[IDX_BITS-1:0];
        for (i = 0; i < N_PALETTES; i = i + 1)
            palette_playlist[i] <= i[PAL_BITS-1:0];
    end else begin
        if (unused_ok) begin end
        free_counter <= free_counter + 16'd1;
        enable_prev <= enable; view_changed <= 1'b0;
        if (seed_pending) begin
            target_lfsr <= 16'hA5C3 ^ target_seed_mix;
            palette_lfsr <= 16'h5E31 ^ palette_seed_mix;
            seed_pending <= 1'b0;
        end else case (state)
        S_SHUFFLE: begin
            active <= 1'b0;
            if (!shuffle_phase) begin
                target_lfsr <= next_target_lfsr2;
                if (target_shuffle_accept) begin
                    target_playlist[shuffle_idx]        <= target_lo_val;
                    target_playlist[shuffle_target_j]   <= target_hi_val;
                    if (shuffle_idx == IDX_ONE) begin
                        shuffle_phase <= 1'b1;
                        shuffle_idx   <= {{(IDX_BITS-PAL_BITS){1'b0}}, PALETTE_LAST_IDX};
                    end else begin
                        shuffle_idx <= shuffle_idx - IDX_ONE;
                    end
                end
            end else begin
                palette_lfsr <= next_palette_lfsr2;
                if (palette_shuffle_accept) begin
                    palette_playlist[shuffle_idx[PAL_BITS-1:0]]        <= palette_lo_val;
                    palette_playlist[shuffle_palette_j[PAL_BITS-1:0]]  <= palette_hi_val;
                    if (shuffle_idx == IDX_ONE) begin
                        target_idx          <= target_playlist[0];
                        palette_idx         <= palette_first_val;
                        target_playlist_pos <= IDX_ONE;
                        palette_playlist_pos<= PAL_ONE;
                        state <= S_LOAD;
                    end else begin
                        shuffle_idx <= shuffle_idx - IDX_ONE;
                    end
                end
            end
        end
        S_LOAD: begin
            if (!enable) begin
                active <= 1'b0;
                state <= S_IDLE;
            end else if (snap_next) begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= snap_step;
                view_changed <= 1'b1;
                active <= 1'b1;
                state <= S_HOLD;
            end else begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= DEFAULT_STEP;
                zoom_steps <= 16'd0;
                dwell_count <= 10'd0;
                active <= 1'b1;
                view_changed <= 1'b1;
                next_loaded <= 1'b0;
                zoom_out_final_pending <= 1'b0;
                state <= S_ZOOM_IN;
            end
        end
        S_IDLE: begin
            active <= 1'b0;
            if (enable_rise) begin
                center_x<=rom_cx; center_y<=rom_cy; step<=DEFAULT_STEP;
                zoom_steps<=16'd0; dwell_count<=10'd0;
                active<=1'b1; view_changed<=1'b1; zoom_out_final_pending<=1'b0; state<=S_ZOOM_IN;
            end else if (snap_next && enable) begin
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= snap_step;
                view_changed <= 1'b1;
                active <= 1'b1;
                state <= S_HOLD;
            end
        end
        S_ZOOM_IN: begin
            if (!enable) begin active<=1'b0; state<=S_IDLE; dwell_count<=10'd0; zoom_out_final_pending<=1'b0; end
            else if (snap_next) begin
                // First snap: stay on current target_idx, just snap step depth
                step <= snap_step;
                view_changed <= 1'b1;
                state <= S_HOLD;
            end
            else if (skip_next) begin dwell_count<=10'd0; next_loaded<=1'b0; state<=S_NEXT; end
            else if (frame_done) begin
                if ((step <= MIN_STEP) || (zoom_level_x10 >= target_max_zoom_x10)) begin
                    if (dwell_done) begin
                        dwell_count <= 10'd0;
                        zoom_out_final_pending <= 1'b0;
                        state <= S_ZOOM_OUT;
                    end else begin
                        dwell_count <= dwell_count + 10'd1;
                    end
                end else begin
                    dwell_count <= 10'd0;
                    step <= step - step_delta;
                    zoom_steps <= zoom_steps + 16'd1;
                    view_changed <= 1'b1;
                end
            end
        end
        S_ZOOM_OUT: begin
            if (!enable) begin active<=1'b0; state<=S_IDLE; dwell_count<=10'd0; zoom_out_final_pending<=1'b0; end
            else if (snap_next) begin
                step <= snap_step;
                view_changed <= 1'b1;
                state <= S_HOLD;
            end
            else if (skip_next) begin dwell_count<=10'd0; next_loaded<=1'b0; zoom_out_final_pending<=1'b0; state<=S_NEXT; end
            else if (frame_done) begin
                if (zoom_out_final_pending) begin
                    zoom_out_final_pending <= 1'b0;
                    next_loaded <= 1'b0;
                    dwell_count <= 10'd0;
                    state <= S_NEXT;
                end else if (zoom_steps == 16'd0) begin
                    step <= DEFAULT_STEP;
                    view_changed <= 1'b1;
                    zoom_out_final_pending <= 1'b1;
                end else begin
                    step <= step + step_delta;
                    zoom_steps <= zoom_steps - 16'd1;
                    view_changed <= 1'b1;
                end
            end
        end
        S_NEXT: begin
            if (!enable) begin active<=1'b0; state<=S_IDLE; dwell_count<=10'd0; end
            else if (!next_loaded) begin
                target_idx <= target_playlist[target_playlist_pos];
                palette_idx <= palette_playlist[palette_playlist_pos];
                target_playlist_pos  <= (target_playlist_pos  == TARGET_LAST_IDX)  ? IDX_ZERO : (target_playlist_pos  + IDX_ONE);
                palette_playlist_pos <= (palette_playlist_pos == PALETTE_LAST_IDX) ? PAL_ZERO : (palette_playlist_pos + PAL_ONE);
                next_loaded <= 1'b1;
            end else begin
                center_x<=rom_cx; center_y<=rom_cy; step<=DEFAULT_STEP;
                zoom_steps<=16'd0; dwell_count<=10'd0;
                view_changed<=1'b1; state<=S_ZOOM_IN;
            end
        end
        S_HOLD: begin
            // Static hold at canonical zoom. Exits on:
            //   - !enable: drop to S_IDLE (Z toggled off)
            //   - snap_next: advance playlist + re-snap (S_SNAP_LOAD)
            //   - skip_next: advance + start a normal zoom-in (S_NEXT)
            if (!enable) begin
                active <= 1'b0;
                state <= S_IDLE;
            end else if (snap_next) begin
                next_loaded <= 1'b0;
                state <= S_SNAP_LOAD;
            end else if (skip_next) begin
                dwell_count<=10'd0; next_loaded<=1'b0;
                zoom_out_final_pending<=1'b0;
                state<=S_NEXT;
            end
        end
        S_SNAP_LOAD: begin
            if (!enable) begin
                active <= 1'b0;
                state <= S_IDLE;
            end else if (!next_loaded) begin
                // Cycle 1: advance playlist, latch new target_idx
                target_idx <= target_playlist[target_playlist_pos];
                palette_idx <= palette_playlist[palette_playlist_pos];
                target_playlist_pos  <= (target_playlist_pos  == TARGET_LAST_IDX)  ? IDX_ZERO : (target_playlist_pos  + IDX_ONE);
                palette_playlist_pos <= (palette_playlist_pos == PALETTE_LAST_IDX) ? PAL_ZERO : (palette_playlist_pos + PAL_ONE);
                next_loaded <= 1'b1;
            end else begin
                // Cycle 2: rom_cx/rom_cy and target_zoom_int now reflect new target_idx
                center_x <= rom_cx;
                center_y <= rom_cy;
                step <= snap_step;
                view_changed <= 1'b1;
                active <= 1'b1;
                state <= S_HOLD;
            end
        end
        default: state <= S_IDLE;
        endcase
    end
end

endmodule
