// AUTO-GENERATED by tools/poi_encode.py — do not edit by hand.
// Source: tools/poi_master.json (74 POIs, idx_bits=7)

`define POI_N_TARGETS  74
`define POI_IDX_BITS   7
`define POI_LAST_IDX   7'd73

// ---- rom_cx / rom_cy (auto_zoom.v) ----
`define POI_ROM_CASES \
    7'd0  : begin rom_cx = 64'shFF40000000000000; rom_cy = 64'sh0000000000000000; end /* WHOLE SET */ \
    7'd1  : begin rom_cx = 64'sh0040000000000000; rom_cy = 64'sh0000000000000000; end /* MAIN CUSP */ \
    7'd2  : begin rom_cx = 64'shFE4CCCCCCCCCCCD0; rom_cy = 64'sh0000000000000000; end /* UTTER WEST */ \
    7'd3  : begin rom_cx = 64'shFF00000000000000; rom_cy = 64'sh0000000000000000; end /* P2 BULB CENTER */ \
    7'd4  : begin rom_cx = 64'shFFE09FD7A13C254A; rom_cy = 64'sh00BEAF46AA087CA8; end /* P3 NORTH BULB */ \
    7'd5  : begin rom_cx = 64'shFFE09FD7A13C254A; rom_cy = 64'shFF4150B955F78358; end /* P3 SOUTH BULB */ \
    7'd6  : begin rom_cx = 64'sh004842E9899BF594; rom_cy = 64'sh0087B213E3E29308; end /* P4 NE BULB */ \
    7'd7  : begin rom_cx = 64'sh004842E9899BF594; rom_cy = 64'shFF784DEC1C1D6CF8; end /* P4 SE BULB */ \
    7'd8  : begin rom_cx = 64'shFEB075CAAE1FC9B0; rom_cy = 64'sh0000000000000000; end /* P4 CASCADE */ \
    7'd9  : begin rom_cx = 64'shFF74E3BCD35A8588; rom_cy = 64'sh009CFAACD9E83E40; end /* P5 2/5 BULB */ \
    7'd10 : begin rom_cx = 64'sh0061234EB9A176DC; rom_cy = 64'sh005626A22B3892F0; end /* P5 1/5 BULB */ \
    7'd11 : begin rom_cx = 64'shFE85CD8127B2CC70; rom_cy = 64'sh0000000000000000; end /* P6 SUB BULB */ \
    7'd12 : begin rom_cx = 64'shFE3EC056580C97A0; rom_cy = 64'sh0000000000000000; end /* P3 ISLAND */ \
    7'd13 : begin rom_cx = 64'shFE35AD18F4BAF4D0; rom_cy = 64'sh0000000000000000; end /* P3 ISLAND TIP */ \
    7'd14 : begin rom_cx = 64'shFFD7EE4E26D48020; rom_cy = 64'sh01084156E264E480; end /* P4 ISLAND */ \
    7'd15 : begin rom_cx = 64'sh005BC2224EDF6124; rom_cy = 64'sh00A4BCDFEFBF4020; end /* P5 ISLAND */ \
    7'd16 : begin rom_cx = 64'sh007167CAEA747D80; rom_cy = 64'sh005FAC929AA1D754; end /* P6 ISLAND */ \
    7'd17 : begin rom_cx = 64'sh006EA8869C66D374; rom_cy = 64'sh003A3150DAE3E6C4; end /* P7 ISLAND */ \
    7'd18 : begin rom_cx = 64'sh0067A6266FD651B0; rom_cy = 64'sh00256E696A26E548; end /* P8 ISLAND */ \
    7'd19 : begin rom_cx = 64'sh0060EDF612407464; rom_cy = 64'sh00194DA4CE8101F3; end /* P9 ISLAND */ \
    7'd20 : begin rom_cx = 64'sh0056E675147F1304; rom_cy = 64'sh000D02BC72E275AC; end /* P11 ISLAND */ \
    7'd21 : begin rom_cx = 64'sh0045AB9F559B3D08; rom_cy = 64'sh000161F5BE5D9E41; end /* P22 ISLAND */ \
    7'd22 : begin rom_cx = 64'sh0046666666666668; rom_cy = 64'sh0001EB851EB851EC; end /* ELEPHANT VALLEY */ \
    7'd23 : begin rom_cx = 64'sh004C5F5AD96A6A00; rom_cy = 64'sh000048BEB5B2D4D4; end /* ELEPHANT TRUNK */ \
    7'd24 : begin rom_cx = 64'sh004AAA8EB463497C; rom_cy = 64'shFFFC049667B5F1BF; end /* ELEPHANT HEADS */ \
    7'd25 : begin rom_cx = 64'sh004AE642BF9830E4; rom_cy = 64'shFFFC2917507E9D95; end /* ELEPHANT ISLAND */ \
    7'd26 : begin rom_cx = 64'sh0047AA25D8D79D0C; rom_cy = 64'sh0002358298CC1440; end /* ELEPHANT P19 */ \
    7'd27 : begin rom_cx = 64'sh004AE32E3821AF7C; rom_cy = 64'sh0003D512EC6BCE85; end /* ELEPHANT P16 */ \
    7'd28 : begin rom_cx = 64'shFF40000000000000; rom_cy = 64'sh001999999999999A; end /* SEAHORSE VALLEY */ \
    7'd29 : begin rom_cx = 64'shFF3E00D1B71758E0; rom_cy = 64'sh00194AF4F0D844D0; end /* SEAHORSE ENTRY */ \
    7'd30 : begin rom_cx = 64'shFF41C8C9320D9948; rom_cy = 64'sh00205DE9C0229A5E; end /* SEAHORSE BODY */ \
    7'd31 : begin rom_cx = 64'shFF41A599821CA550; rom_cy = 64'sh0021A394C51E82A2; end /* SEAHORSE TAIL */ \
    7'd32 : begin rom_cx = 64'shFF4184A0E410B630; rom_cy = 64'sh001E0DED288CE704; end /* SEAHORSE DEEP */ \
    7'd33 : begin rom_cx = 64'shFF41A028FFD38A58; rom_cy = 64'sh0021C30578BAD1CE; end /* SEAHORSE TAIL2 */ \
    7'd34 : begin rom_cx = 64'shFF41A0C0D547C590; rom_cy = 64'sh0021BF6F9711A9F6; end /* DOUBLE HOOK */ \
    7'd35 : begin rom_cx = 64'shFF41A09A7F47B3C8; rom_cy = 64'sh0021BF58A7D944CC; end /* SH SATELLITE */ \
    7'd36 : begin rom_cx = 64'shFF41A07ECC4A0140; rom_cy = 64'sh0021BF4CC0FFB852; end /* SAT ANTENNA */ \
    7'd37 : begin rom_cx = 64'shFF41A08A504FCA80; rom_cy = 64'sh0021BF5A101C4DD8; end /* SAT HEAD */ \
    7'd38 : begin rom_cx = 64'shFF41A08E49E015F8; rom_cy = 64'sh0021BF57A4E7B674; end /* SAT SEAHORSE */ \
    7'd39 : begin rom_cx = 64'shFF41A08DA964D578; rom_cy = 64'sh0021BF57722F9474; end /* SAT DBL SPIRAL */ \
    7'd40 : begin rom_cx = 64'shFF41A08DDA97BD58; rom_cy = 64'sh0021BF57ABBBEFAA; end /* JULIA ISLANDS */ \
    7'd41 : begin rom_cx = 64'shFFE99375932A13D0; rom_cy = 64'sh00A7B3FDC8EE1AF8; end /* TRIPLE SPIRAL */ \
    7'd42 : begin rom_cx = 64'shFFD858793DD97F62; rom_cy = 64'sh00A6F544BB1AF3A0; end /* TRIPLE WEST */ \
    7'd43 : begin rom_cx = 64'shFFD8000000000000; rom_cy = 64'sh00A745F17BD8BE70; end /* TRIPLE DEEP */ \
    7'd44 : begin rom_cx = 64'shFE994DE4BE9FD230; rom_cy = 64'sh0000000000000000; end /* FEIGENBAUM */ \
    7'd45 : begin rom_cx = 64'shFE994EE392E1EF70; rom_cy = 64'sh0000000000000000; end /* FEIGENBAUM ZOOM */ \
    7'd46 : begin rom_cx = 64'shFE994DE48F613170; rom_cy = 64'sh0000000000000000; end /* FEIGENBAUM DEEP */ \
    7'd47 : begin rom_cx = 64'shFFD8E219652BD3C4; rom_cy = 64'sh010A29C779A6B510; end /* GEN FEIGENBAUM */ \
    7'd48 : begin rom_cx = 64'shFE74D0CC0243F470; rom_cy = 64'sh0000000000000000; end /* MISIUREWICZ M3 */ \
    7'd49 : begin rom_cx = 64'sh0000000000000000; rom_cy = 64'sh0100000000000000; end /* MISIUREWICZ I */ \
    7'd50 : begin rom_cx = 64'shFFC59799FEDE05CA; rom_cy = 64'sh011D79FABA3D4A80; end /* MISIUREWICZ M3 NE */ \
    7'd51 : begin rom_cx = 64'shFFE61E8C76E02000; rom_cy = 64'sh00F4CF31560E5480; end /* MISIUREWICZ M4 */ \
    7'd52 : begin rom_cx = 64'sh005DC9F6E6733374; rom_cy = 64'sh00976EC1E183B578; end /* MISIUREWICZ M4-2 */ \
    7'd53 : begin rom_cx = 64'shFF396CC9D7CFE028; rom_cy = 64'sh0022EF868B1F027A; end /* MISIUREWICZ SPIR */ \
    7'd54 : begin rom_cx = 64'shFE0F27BE6CDA1550; rom_cy = 64'sh0000000000000000; end /* MISIUREWICZ -1.94 */ \
    7'd55 : begin rom_cx = 64'shFE29247CB70AC3B0; rom_cy = 64'sh0000000000000000; end /* MISIUREWICZ -1.84 */ \
    7'd56 : begin rom_cx = 64'shFFD6C0EB173AAF28; rom_cy = 64'sh01094C668AF96DC0; end /* DBL SPIRAL P4 */ \
    7'd57 : begin rom_cx = 64'shFFD87A19A191B5A0; rom_cy = 64'sh0107E4712E408530; end /* SINGLE SPIRAL */ \
    7'd58 : begin rom_cx = 64'shFFD890FA8EA6F750; rom_cy = 64'sh010973BAE2BF7D60; end /* TRIPLE MEDALLION */ \
    7'd59 : begin rom_cx = 64'shFEBEA36AFEA68EA0; rom_cy = 64'shFF9E278EE535A450; end /* DBL SPIRAL ISLE */ \
    7'd60 : begin rom_cx = 64'shFEBECC9D7CFE0280; rom_cy = 64'shFF9EE5C5413D3718; end /* TRIPLE ISLE MED */ \
    7'd61 : begin rom_cx = 64'shFEBE3C0AF32322C0; rom_cy = 64'shFF9ED201EAE6BE3C; end /* CAULIFLOWER MED */ \
    7'd62 : begin rom_cx = 64'shFE4050F769588930; rom_cy = 64'sh0000000000000000; end /* EJS CAULI */ \
    7'd63 : begin rom_cx = 64'shFE3B3BAB40A4CFA0; rom_cy = 64'sh00009F23A91EEA1D; end /* EJS DBL SPIRAL */ \
    7'd64 : begin rom_cx = 64'shFE3E0856948DF660; rom_cy = 64'sh0004865AF6BC4C86; end /* EJS BRANCH */ \
    7'd65 : begin rom_cx = 64'shFF4165D5F1716E70; rom_cy = 64'sh001F294A0AC1F92A; end /* EJS NUCLEUS */ \
    7'd66 : begin rom_cx = 64'shFFD464CB5BB384FE; rom_cy = 64'shFEEF583A53B8E4C0; end /* BOURKE LIGHTNING */ \
    7'd67 : begin rom_cx = 64'shFE5EEEB702602C90; rom_cy = 64'shFFFAC7467B0E9418; end /* BOURKE FILAMENT */ \
    7'd68 : begin rom_cx = 64'shFF3D097C80841EE0; rom_cy = 64'shFFEA4D31E1FA5B7B; end /* BOURKE SPIRAL */ \
    7'd69 : begin rom_cx = 64'shFF39AE8810A0B038; rom_cy = 64'shFFDCD23F3A6E091E; end /* TANTE RENATE */ \
    7'd70 : begin rom_cx = 64'shFFC3CED916872B02; rom_cy = 64'sh00D3C504816F0068; end /* LOVE CANAL */ \
    7'd71 : begin rom_cx = 64'sh005BF8699E294B54; rom_cy = 64'sh00A47BC7BFA54F90; end /* P5 ISLAND DEEP */ \
    7'd72 : begin rom_cx = 64'sh004288C7A07942F4; rom_cy = 64'sh000069AF2C641D47; end /* ELEPHANT MED */ \
    7'd73 : begin rom_cx = 64'shFFA04143C66D260C; rom_cy = 64'sh00A8E823D5C81E10; end /* STARFISH */

// ---- target_max_zoom_x10 (auto_zoom.v) — POI canonical zoom (×10) ----
`define POI_ZOOM_CASES \
    7'd0  : target_max_zoom_x10 = 10'd0; /* WHOLE SET */ \
    7'd1  : target_max_zoom_x10 = 10'd40; /* MAIN CUSP */ \
    7'd2  : target_max_zoom_x10 = 10'd20; /* UTTER WEST */ \
    7'd3  : target_max_zoom_x10 = 10'd15; /* P2 BULB CENTER */ \
    7'd4  : target_max_zoom_x10 = 10'd25; /* P3 NORTH BULB */ \
    7'd5  : target_max_zoom_x10 = 10'd25; /* P3 SOUTH BULB */ \
    7'd6  : target_max_zoom_x10 = 10'd40; /* P4 NE BULB */ \
    7'd7  : target_max_zoom_x10 = 10'd40; /* P4 SE BULB */ \
    7'd8  : target_max_zoom_x10 = 10'd30; /* P4 CASCADE */ \
    7'd9  : target_max_zoom_x10 = 10'd40; /* P5 2/5 BULB */ \
    7'd10 : target_max_zoom_x10 = 10'd40; /* P5 1/5 BULB */ \
    7'd11 : target_max_zoom_x10 = 10'd60; /* P6 SUB BULB */ \
    7'd12 : target_max_zoom_x10 = 10'd50; /* P3 ISLAND */ \
    7'd13 : target_max_zoom_x10 = 10'd70; /* P3 ISLAND TIP */ \
    7'd14 : target_max_zoom_x10 = 10'd60; /* P4 ISLAND */ \
    7'd15 : target_max_zoom_x10 = 10'd70; /* P5 ISLAND */ \
    7'd16 : target_max_zoom_x10 = 10'd70; /* P6 ISLAND */ \
    7'd17 : target_max_zoom_x10 = 10'd80; /* P7 ISLAND */ \
    7'd18 : target_max_zoom_x10 = 10'd80; /* P8 ISLAND */ \
    7'd19 : target_max_zoom_x10 = 10'd90; /* P9 ISLAND */ \
    7'd20 : target_max_zoom_x10 = 10'd100; /* P11 ISLAND */ \
    7'd21 : target_max_zoom_x10 = 10'd120; /* P22 ISLAND */ \
    7'd22 : target_max_zoom_x10 = 10'd40; /* ELEPHANT VALLEY */ \
    7'd23 : target_max_zoom_x10 = 10'd50; /* ELEPHANT TRUNK */ \
    7'd24 : target_max_zoom_x10 = 10'd90; /* ELEPHANT HEADS */ \
    7'd25 : target_max_zoom_x10 = 10'd130; /* ELEPHANT ISLAND */ \
    7'd26 : target_max_zoom_x10 = 10'd110; /* ELEPHANT P19 */ \
    7'd27 : target_max_zoom_x10 = 10'd110; /* ELEPHANT P16 */ \
    7'd28 : target_max_zoom_x10 = 10'd40; /* SEAHORSE VALLEY */ \
    7'd29 : target_max_zoom_x10 = 10'd46; /* SEAHORSE ENTRY */ \
    7'd30 : target_max_zoom_x10 = 10'd80; /* SEAHORSE BODY */ \
    7'd31 : target_max_zoom_x10 = 10'd108; /* SEAHORSE TAIL */ \
    7'd32 : target_max_zoom_x10 = 10'd84; /* SEAHORSE DEEP */ \
    7'd33 : target_max_zoom_x10 = 10'd124; /* SEAHORSE TAIL2 */ \
    7'd34 : target_max_zoom_x10 = 10'd149; /* DOUBLE HOOK */ \
    7'd35 : target_max_zoom_x10 = 10'd181; /* SH SATELLITE */ \
    7'd36 : target_max_zoom_x10 = 10'd203; /* SAT ANTENNA */ \
    7'd37 : target_max_zoom_x10 = 10'd225; /* SAT HEAD */ \
    7'd38 : target_max_zoom_x10 = 10'd248; /* SAT SEAHORSE */ \
    7'd39 : target_max_zoom_x10 = 10'd263; /* SAT DBL SPIRAL */ \
    7'd40 : target_max_zoom_x10 = 10'd298; /* JULIA ISLANDS */ \
    7'd41 : target_max_zoom_x10 = 10'd40; /* TRIPLE SPIRAL */ \
    7'd42 : target_max_zoom_x10 = 10'd90; /* TRIPLE WEST */ \
    7'd43 : target_max_zoom_x10 = 10'd120; /* TRIPLE DEEP */ \
    7'd44 : target_max_zoom_x10 = 10'd50; /* FEIGENBAUM */ \
    7'd45 : target_max_zoom_x10 = 10'd70; /* FEIGENBAUM ZOOM */ \
    7'd46 : target_max_zoom_x10 = 10'd130; /* FEIGENBAUM DEEP */ \
    7'd47 : target_max_zoom_x10 = 10'd60; /* GEN FEIGENBAUM */ \
    7'd48 : target_max_zoom_x10 = 10'd40; /* MISIUREWICZ M3 */ \
    7'd49 : target_max_zoom_x10 = 10'd40; /* MISIUREWICZ I */ \
    7'd50 : target_max_zoom_x10 = 10'd40; /* MISIUREWICZ M3 NE */ \
    7'd51 : target_max_zoom_x10 = 10'd60; /* MISIUREWICZ M4 */ \
    7'd52 : target_max_zoom_x10 = 10'd50; /* MISIUREWICZ M4-2 */ \
    7'd53 : target_max_zoom_x10 = 10'd70; /* MISIUREWICZ SPIR */ \
    7'd54 : target_max_zoom_x10 = 10'd70; /* MISIUREWICZ -1.94 */ \
    7'd55 : target_max_zoom_x10 = 10'd60; /* MISIUREWICZ -1.84 */ \
    7'd56 : target_max_zoom_x10 = 10'd60; /* DBL SPIRAL P4 */ \
    7'd57 : target_max_zoom_x10 = 10'd60; /* SINGLE SPIRAL */ \
    7'd58 : target_max_zoom_x10 = 10'd70; /* TRIPLE MEDALLION */ \
    7'd59 : target_max_zoom_x10 = 10'd230; /* DBL SPIRAL ISLE */ \
    7'd60 : target_max_zoom_x10 = 10'd225; /* TRIPLE ISLE MED */ \
    7'd61 : target_max_zoom_x10 = 10'd216; /* CAULIFLOWER MED */ \
    7'd62 : target_max_zoom_x10 = 10'd173; /* EJS CAULI */ \
    7'd63 : target_max_zoom_x10 = 10'd187; /* EJS DBL SPIRAL */ \
    7'd64 : target_max_zoom_x10 = 10'd233; /* EJS BRANCH */ \
    7'd65 : target_max_zoom_x10 = 10'd270; /* EJS NUCLEUS */ \
    7'd66 : target_max_zoom_x10 = 10'd40; /* BOURKE LIGHTNING */ \
    7'd67 : target_max_zoom_x10 = 10'd40; /* BOURKE FILAMENT */ \
    7'd68 : target_max_zoom_x10 = 10'd40; /* BOURKE SPIRAL */ \
    7'd69 : target_max_zoom_x10 = 10'd60; /* TANTE RENATE */ \
    7'd70 : target_max_zoom_x10 = 10'd120; /* LOVE CANAL */ \
    7'd71 : target_max_zoom_x10 = 10'd80; /* P5 ISLAND DEEP */ \
    7'd72 : target_max_zoom_x10 = 10'd140; /* ELEPHANT MED */ \
    7'd73 : target_max_zoom_x10 = 10'd160; /* STARFISH */

// ---- target_zoom_int (auto_zoom.v) — integer shift amount for snap ----
`define POI_ZOOM_INT_CASES \
    7'd0  : target_zoom_int = 5'd0; /* WHOLE SET */ \
    7'd1  : target_zoom_int = 5'd4; /* MAIN CUSP */ \
    7'd2  : target_zoom_int = 5'd2; /* UTTER WEST */ \
    7'd3  : target_zoom_int = 5'd2; /* P2 BULB CENTER */ \
    7'd4  : target_zoom_int = 5'd2; /* P3 NORTH BULB */ \
    7'd5  : target_zoom_int = 5'd2; /* P3 SOUTH BULB */ \
    7'd6  : target_zoom_int = 5'd4; /* P4 NE BULB */ \
    7'd7  : target_zoom_int = 5'd4; /* P4 SE BULB */ \
    7'd8  : target_zoom_int = 5'd3; /* P4 CASCADE */ \
    7'd9  : target_zoom_int = 5'd4; /* P5 2/5 BULB */ \
    7'd10 : target_zoom_int = 5'd4; /* P5 1/5 BULB */ \
    7'd11 : target_zoom_int = 5'd6; /* P6 SUB BULB */ \
    7'd12 : target_zoom_int = 5'd5; /* P3 ISLAND */ \
    7'd13 : target_zoom_int = 5'd7; /* P3 ISLAND TIP */ \
    7'd14 : target_zoom_int = 5'd6; /* P4 ISLAND */ \
    7'd15 : target_zoom_int = 5'd7; /* P5 ISLAND */ \
    7'd16 : target_zoom_int = 5'd7; /* P6 ISLAND */ \
    7'd17 : target_zoom_int = 5'd8; /* P7 ISLAND */ \
    7'd18 : target_zoom_int = 5'd8; /* P8 ISLAND */ \
    7'd19 : target_zoom_int = 5'd9; /* P9 ISLAND */ \
    7'd20 : target_zoom_int = 5'd10; /* P11 ISLAND */ \
    7'd21 : target_zoom_int = 5'd12; /* P22 ISLAND */ \
    7'd22 : target_zoom_int = 5'd4; /* ELEPHANT VALLEY */ \
    7'd23 : target_zoom_int = 5'd5; /* ELEPHANT TRUNK */ \
    7'd24 : target_zoom_int = 5'd9; /* ELEPHANT HEADS */ \
    7'd25 : target_zoom_int = 5'd13; /* ELEPHANT ISLAND */ \
    7'd26 : target_zoom_int = 5'd11; /* ELEPHANT P19 */ \
    7'd27 : target_zoom_int = 5'd11; /* ELEPHANT P16 */ \
    7'd28 : target_zoom_int = 5'd4; /* SEAHORSE VALLEY */ \
    7'd29 : target_zoom_int = 5'd5; /* SEAHORSE ENTRY */ \
    7'd30 : target_zoom_int = 5'd8; /* SEAHORSE BODY */ \
    7'd31 : target_zoom_int = 5'd11; /* SEAHORSE TAIL */ \
    7'd32 : target_zoom_int = 5'd8; /* SEAHORSE DEEP */ \
    7'd33 : target_zoom_int = 5'd12; /* SEAHORSE TAIL2 */ \
    7'd34 : target_zoom_int = 5'd15; /* DOUBLE HOOK */ \
    7'd35 : target_zoom_int = 5'd18; /* SH SATELLITE */ \
    7'd36 : target_zoom_int = 5'd20; /* SAT ANTENNA */ \
    7'd37 : target_zoom_int = 5'd22; /* SAT HEAD */ \
    7'd38 : target_zoom_int = 5'd25; /* SAT SEAHORSE */ \
    7'd39 : target_zoom_int = 5'd26; /* SAT DBL SPIRAL */ \
    7'd40 : target_zoom_int = 5'd30; /* JULIA ISLANDS */ \
    7'd41 : target_zoom_int = 5'd4; /* TRIPLE SPIRAL */ \
    7'd42 : target_zoom_int = 5'd9; /* TRIPLE WEST */ \
    7'd43 : target_zoom_int = 5'd12; /* TRIPLE DEEP */ \
    7'd44 : target_zoom_int = 5'd5; /* FEIGENBAUM */ \
    7'd45 : target_zoom_int = 5'd7; /* FEIGENBAUM ZOOM */ \
    7'd46 : target_zoom_int = 5'd13; /* FEIGENBAUM DEEP */ \
    7'd47 : target_zoom_int = 5'd6; /* GEN FEIGENBAUM */ \
    7'd48 : target_zoom_int = 5'd4; /* MISIUREWICZ M3 */ \
    7'd49 : target_zoom_int = 5'd4; /* MISIUREWICZ I */ \
    7'd50 : target_zoom_int = 5'd4; /* MISIUREWICZ M3 NE */ \
    7'd51 : target_zoom_int = 5'd6; /* MISIUREWICZ M4 */ \
    7'd52 : target_zoom_int = 5'd5; /* MISIUREWICZ M4-2 */ \
    7'd53 : target_zoom_int = 5'd7; /* MISIUREWICZ SPIR */ \
    7'd54 : target_zoom_int = 5'd7; /* MISIUREWICZ -1.94 */ \
    7'd55 : target_zoom_int = 5'd6; /* MISIUREWICZ -1.84 */ \
    7'd56 : target_zoom_int = 5'd6; /* DBL SPIRAL P4 */ \
    7'd57 : target_zoom_int = 5'd6; /* SINGLE SPIRAL */ \
    7'd58 : target_zoom_int = 5'd7; /* TRIPLE MEDALLION */ \
    7'd59 : target_zoom_int = 5'd23; /* DBL SPIRAL ISLE */ \
    7'd60 : target_zoom_int = 5'd22; /* TRIPLE ISLE MED */ \
    7'd61 : target_zoom_int = 5'd22; /* CAULIFLOWER MED */ \
    7'd62 : target_zoom_int = 5'd17; /* EJS CAULI */ \
    7'd63 : target_zoom_int = 5'd19; /* EJS DBL SPIRAL */ \
    7'd64 : target_zoom_int = 5'd23; /* EJS BRANCH */ \
    7'd65 : target_zoom_int = 5'd27; /* EJS NUCLEUS */ \
    7'd66 : target_zoom_int = 5'd4; /* BOURKE LIGHTNING */ \
    7'd67 : target_zoom_int = 5'd4; /* BOURKE FILAMENT */ \
    7'd68 : target_zoom_int = 5'd4; /* BOURKE SPIRAL */ \
    7'd69 : target_zoom_int = 5'd6; /* TANTE RENATE */ \
    7'd70 : target_zoom_int = 5'd12; /* LOVE CANAL */ \
    7'd71 : target_zoom_int = 5'd8; /* P5 ISLAND DEEP */ \
    7'd72 : target_zoom_int = 5'd14; /* ELEPHANT MED */ \
    7'd73 : target_zoom_int = 5'd16; /* STARFISH */

// ---- target_name_full (text_overlay.v) — 20-char overlay label ----
`define POI_NAME_CASES \
    7'd0  : target_name_full = "WHOLE SET           "; /* WHOLE SET */ \
    7'd1  : target_name_full = "MAIN CUSP           "; /* MAIN CUSP */ \
    7'd2  : target_name_full = "UTTER WEST          "; /* UTTER WEST */ \
    7'd3  : target_name_full = "P2 BULB CENTER      "; /* P2 BULB CENTER */ \
    7'd4  : target_name_full = "P3 NORTH BULB       "; /* P3 NORTH BULB */ \
    7'd5  : target_name_full = "P3 SOUTH BULB       "; /* P3 SOUTH BULB */ \
    7'd6  : target_name_full = "P4 NE BULB          "; /* P4 NE BULB */ \
    7'd7  : target_name_full = "P4 SE BULB          "; /* P4 SE BULB */ \
    7'd8  : target_name_full = "P4 CASCADE          "; /* P4 CASCADE */ \
    7'd9  : target_name_full = "P5 25 BULB          "; /* P5 2/5 BULB */ \
    7'd10 : target_name_full = "P5 15 BULB          "; /* P5 1/5 BULB */ \
    7'd11 : target_name_full = "P6 SUB BULB         "; /* P6 SUB BULB */ \
    7'd12 : target_name_full = "P3 ISLAND           "; /* P3 ISLAND */ \
    7'd13 : target_name_full = "P3 ISLAND TIP       "; /* P3 ISLAND TIP */ \
    7'd14 : target_name_full = "P4 ISLAND           "; /* P4 ISLAND */ \
    7'd15 : target_name_full = "P5 ISLAND           "; /* P5 ISLAND */ \
    7'd16 : target_name_full = "P6 ISLAND           "; /* P6 ISLAND */ \
    7'd17 : target_name_full = "P7 ISLAND           "; /* P7 ISLAND */ \
    7'd18 : target_name_full = "P8 ISLAND           "; /* P8 ISLAND */ \
    7'd19 : target_name_full = "P9 ISLAND           "; /* P9 ISLAND */ \
    7'd20 : target_name_full = "P11 ISLAND          "; /* P11 ISLAND */ \
    7'd21 : target_name_full = "P22 ISLAND          "; /* P22 ISLAND */ \
    7'd22 : target_name_full = "ELEPHANT VALLEY     "; /* ELEPHANT VALLEY */ \
    7'd23 : target_name_full = "ELEPHANT TRUNK      "; /* ELEPHANT TRUNK */ \
    7'd24 : target_name_full = "ELEPHANT HEADS      "; /* ELEPHANT HEADS */ \
    7'd25 : target_name_full = "ELEPHANT ISLAND     "; /* ELEPHANT ISLAND */ \
    7'd26 : target_name_full = "ELEPHANT P19        "; /* ELEPHANT P19 */ \
    7'd27 : target_name_full = "ELEPHANT P16        "; /* ELEPHANT P16 */ \
    7'd28 : target_name_full = "SEAHORSE VALLEY     "; /* SEAHORSE VALLEY */ \
    7'd29 : target_name_full = "SEAHORSE ENTRY      "; /* SEAHORSE ENTRY */ \
    7'd30 : target_name_full = "SEAHORSE BODY       "; /* SEAHORSE BODY */ \
    7'd31 : target_name_full = "SEAHORSE TAIL       "; /* SEAHORSE TAIL */ \
    7'd32 : target_name_full = "SEAHORSE DEEP       "; /* SEAHORSE DEEP */ \
    7'd33 : target_name_full = "SEAHORSE TAIL2      "; /* SEAHORSE TAIL2 */ \
    7'd34 : target_name_full = "DOUBLE HOOK         "; /* DOUBLE HOOK */ \
    7'd35 : target_name_full = "SH SATELLITE        "; /* SH SATELLITE */ \
    7'd36 : target_name_full = "SAT ANTENNA         "; /* SAT ANTENNA */ \
    7'd37 : target_name_full = "SAT HEAD            "; /* SAT HEAD */ \
    7'd38 : target_name_full = "SAT SEAHORSE        "; /* SAT SEAHORSE */ \
    7'd39 : target_name_full = "SAT DBL SPIRAL      "; /* SAT DBL SPIRAL */ \
    7'd40 : target_name_full = "JULIA ISLANDS       "; /* JULIA ISLANDS */ \
    7'd41 : target_name_full = "TRIPLE SPIRAL       "; /* TRIPLE SPIRAL */ \
    7'd42 : target_name_full = "TRIPLE WEST         "; /* TRIPLE WEST */ \
    7'd43 : target_name_full = "TRIPLE DEEP         "; /* TRIPLE DEEP */ \
    7'd44 : target_name_full = "FEIGENBAUM          "; /* FEIGENBAUM */ \
    7'd45 : target_name_full = "FEIGENBAUM ZOOM     "; /* FEIGENBAUM ZOOM */ \
    7'd46 : target_name_full = "FEIGENBAUM DEEP     "; /* FEIGENBAUM DEEP */ \
    7'd47 : target_name_full = "GEN FEIGENBAUM      "; /* GEN FEIGENBAUM */ \
    7'd48 : target_name_full = "MISIUREWICZ M3      "; /* MISIUREWICZ M3 */ \
    7'd49 : target_name_full = "MISIUREWICZ I       "; /* MISIUREWICZ I */ \
    7'd50 : target_name_full = "MISIUREWICZ M3 NE   "; /* MISIUREWICZ M3 NE */ \
    7'd51 : target_name_full = "MISIUREWICZ M4      "; /* MISIUREWICZ M4 */ \
    7'd52 : target_name_full = "MISIUREWICZ M4-2    "; /* MISIUREWICZ M4-2 */ \
    7'd53 : target_name_full = "MISIUREWICZ SPIR    "; /* MISIUREWICZ SPIR */ \
    7'd54 : target_name_full = "MISIUREWICZ -194    "; /* MISIUREWICZ -1.94 */ \
    7'd55 : target_name_full = "MISIUREWICZ -184    "; /* MISIUREWICZ -1.84 */ \
    7'd56 : target_name_full = "DBL SPIRAL P4       "; /* DBL SPIRAL P4 */ \
    7'd57 : target_name_full = "SINGLE SPIRAL       "; /* SINGLE SPIRAL */ \
    7'd58 : target_name_full = "TRIPLE MEDALLION    "; /* TRIPLE MEDALLION */ \
    7'd59 : target_name_full = "DBL SPIRAL ISLE     "; /* DBL SPIRAL ISLE */ \
    7'd60 : target_name_full = "TRIPLE ISLE MED     "; /* TRIPLE ISLE MED */ \
    7'd61 : target_name_full = "CAULIFLOWER MED     "; /* CAULIFLOWER MED */ \
    7'd62 : target_name_full = "EJS CAULI           "; /* EJS CAULI */ \
    7'd63 : target_name_full = "EJS DBL SPIRAL      "; /* EJS DBL SPIRAL */ \
    7'd64 : target_name_full = "EJS BRANCH          "; /* EJS BRANCH */ \
    7'd65 : target_name_full = "EJS NUCLEUS         "; /* EJS NUCLEUS */ \
    7'd66 : target_name_full = "BOURKE LIGHTNING    "; /* BOURKE LIGHTNING */ \
    7'd67 : target_name_full = "BOURKE FILAMENT     "; /* BOURKE FILAMENT */ \
    7'd68 : target_name_full = "BOURKE SPIRAL       "; /* BOURKE SPIRAL */ \
    7'd69 : target_name_full = "TANTE RENATE        "; /* TANTE RENATE */ \
    7'd70 : target_name_full = "LOVE CANAL          "; /* LOVE CANAL */ \
    7'd71 : target_name_full = "P5 ISLAND DEEP      "; /* P5 ISLAND DEEP */ \
    7'd72 : target_name_full = "ELEPHANT MED        "; /* ELEPHANT MED */ \
    7'd73 : target_name_full = "STARFISH            "; /* STARFISH */
