#!/usr/bin/env python3
"""Encode deterministic benchmark scenes into Verilog case blocks."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCH_JSON = ROOT / "tools" / "benchmarks.json"
OUT_VH = ROOT / "rtl" / "benchmark_generated.vh"

FRAC_BITS = 56
WIDTH = 64
SCALE = 1 << FRAC_BITS
DEFAULT_STEP = 0.0125
MAX_VAL = (1 << (WIDTH - 1)) - 1
MIN_VAL = -(1 << (WIDTH - 1))


def to_8_56(x: float) -> int:
    raw = int(round(x * SCALE))
    if raw > MAX_VAL or raw < MIN_VAL:
        raise ValueError(f"value {x} out of 8.56 range")
    if raw < 0:
        raw += 1 << WIDTH
    return raw


def hex64(u: int) -> str:
    return f"64'sh{u:016X}"


def iter_tier(max_iter: int) -> int:
    tiers = {
        128: 0,
        256: 1,
        512: 2,
        1024: 3,
        2048: 4,
        4095: 5,
    }
    if max_iter not in tiers:
        raise ValueError(f"unsupported max_iter tier: {max_iter}")
    return tiers[max_iter]


def main() -> int:
    if not BENCH_JSON.exists():
        print(f"ERROR: {BENCH_JSON} not found", file=sys.stderr)
        return 1

    scenes = json.loads(BENCH_JSON.read_text())
    n = len(scenes)
    idx_bits = max(4, (n - 1).bit_length())

    encoded = []
    for i, scene in enumerate(scenes):
        zoom = float(scene["zoom_level"])
        step = DEFAULT_STEP / (2.0 ** zoom)
        max_iter = int(scene["max_iter"])
        if max_iter < 1 or max_iter > 4095:
            raise ValueError(f"{scene['name']}: max_iter out of 12-bit range")
        palette = int(scene.get("palette", 0))
        if palette < 0 or palette > 89:
            raise ValueError(f"{scene['name']}: palette out of range")
        encoded.append({
            "idx": i,
            "name": scene["name"],
            "cx": to_8_56(float(scene["cx"])),
            "cy": to_8_56(float(scene["cy"])),
            "step": to_8_56(step),
            "max_iter": max_iter,
            "iter_tier": iter_tier(max_iter),
            "mode_640": 1 if scene.get("mode_640", True) else 0,
            "palette": palette,
        })

    lines = [
        "// AUTO-GENERATED by tools/bench_encode.py - do not edit by hand.",
        f"// Source: tools/benchmarks.json ({n} scenes, idx_bits={idx_bits})",
        "",
        f"`define BENCH_N_SCENES  {n}",
        f"`define BENCH_IDX_BITS   {idx_bits}",
        f"`define BENCH_LAST_IDX   {idx_bits}'d{n - 1}",
        "",
        "// ---- benchmark scene data (fractal_top.v) ----",
        "`define BENCH_SCENE_CASES \\",
    ]
    for e in encoded:
        lines.append(
            f"    {idx_bits}'d{e['idx']:<2}: begin "
            f"bench_center_x = {hex64(e['cx'])}; "
            f"bench_center_y = {hex64(e['cy'])}; "
            f"bench_step = {hex64(e['step'])}; "
            f"bench_max_iter = 12'd{e['max_iter']}; "
            f"bench_iter_tier = 4'd{e['iter_tier']}; "
            f"bench_palette = 7'd{e['palette']}; "
            f"bench_mode_640 = 1'b{e['mode_640']}; "
            f"end /* {e['name']} */ \\"
        )
    lines[-1] = lines[-1].rstrip(" \\")

    OUT_VH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_VH} ({n} scenes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
