#!/usr/bin/env python3
"""Encode POI master list into 8.56 fixed-point Verilog `case` blocks.

Reads tools/poi_master.json. Produces:
  - tools/poi_generated.vh : two `case` blocks (rom_cx/cy, target_max_zoom_x10)
                              and one for target_name_full (text_overlay)
  - prints a roundtrip-verified summary table

8.56 format: 64-bit signed, 56 fractional bits. value = signed_int / 2**56.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER_JSON = ROOT / "tools" / "poi_master.json"
OUT_VH = ROOT / "rtl" / "poi_generated.vh"

FRAC_BITS = 56
WIDTH = 64
SCALE = 1 << FRAC_BITS
MAX_VAL = (1 << (WIDTH - 1)) - 1
MIN_VAL = -(1 << (WIDTH - 1))


def to_8_56(x: float) -> int:
    """Decimal -> signed 64-bit two's complement int representing 8.56 fixed."""
    raw = int(round(x * SCALE))
    if raw > MAX_VAL or raw < MIN_VAL:
        raise ValueError(f"value {x} out of 8.56 range")
    if raw < 0:
        raw += 1 << WIDTH
    return raw


def from_8_56(u: int) -> float:
    if u & (1 << (WIDTH - 1)):
        u -= 1 << WIDTH
    return u / SCALE


def hex64(u: int) -> str:
    return f"64'sh{u:016X}"


def name_to_overlay(s: str, length: int = 20) -> str:
    """Pad/truncate to exactly `length` chars, uppercase, ASCII-safe."""
    s = re.sub(r"[^A-Za-z0-9 \-]", "", s).upper()
    if len(s) > length:
        s = s[:length]
    return s.ljust(length)


def main():
    if not MASTER_JSON.exists():
        print(f"ERROR: {MASTER_JSON} not found.", file=sys.stderr)
        sys.exit(1)
    with open(MASTER_JSON) as f:
        pois = json.load(f)
    n = len(pois)
    idx_bits = max(5, (n - 1).bit_length())
    print(f"Encoding {n} POIs (idx_bits={idx_bits})")

    # Verification
    print(f"\n{'idx':>3} {'name':<22} {'cx':>14} {'cy':>14} zoom  cx_hex                 cy_hex")
    print("-" * 110)
    encoded = []
    for i, p in enumerate(pois):
        cx, cy = float(p["cx"]), float(p["cy"])
        zoom = float(p["zoom_level"])
        name = p["name"]
        cx_u = to_8_56(cx)
        cy_u = to_8_56(cy)
        cx_back = from_8_56(cx_u)
        cy_back = from_8_56(cy_u)
        err = max(abs(cx - cx_back), abs(cy - cy_back))
        if err > 1e-14:
            print(f"  WARN idx {i}: roundtrip error {err:.2e}")
        zoom_x10 = int(round(zoom * 10))
        encoded.append({
            "idx": i,
            "name": name,
            "cx_u": cx_u,
            "cy_u": cy_u,
            "zoom_x10": zoom_x10,
            "overlay": name_to_overlay(name),
        })
        print(f"{i:>3} {name:<22} {cx:>14.10f} {cy:>14.10f} {zoom:5.2f}  {hex64(cx_u)}  {hex64(cy_u)}")

    # Generate Verilog
    lines = []
    lines.append(f"// AUTO-GENERATED by tools/poi_encode.py — do not edit by hand.")
    lines.append(f"// Source: tools/poi_master.json ({n} POIs, idx_bits={idx_bits})")
    lines.append(f"")
    lines.append(f"`define POI_N_TARGETS  {n}")
    lines.append(f"`define POI_IDX_BITS   {idx_bits}")
    lines.append(f"`define POI_LAST_IDX   {idx_bits}'d{n-1}")
    lines.append("")
    lines.append("// ---- rom_cx / rom_cy (auto_zoom.v) ----")
    lines.append("`define POI_ROM_CASES \\")
    for e in encoded:
        lines.append(f"    {idx_bits}'d{e['idx']:<3}: begin rom_cx = {hex64(e['cx_u'])}; rom_cy = {hex64(e['cy_u'])}; end /* {e['name']} */ \\")
    lines[-1] = lines[-1].rstrip(" \\")  # drop trailing slash on last item
    lines.append("")
    lines.append("// ---- target_max_zoom_x10 (auto_zoom.v) — POI canonical zoom (×10) ----")
    lines.append("`define POI_ZOOM_CASES \\")
    for e in encoded:
        lines.append(f"    {idx_bits}'d{e['idx']:<3}: target_max_zoom_x10 = 10'd{e['zoom_x10']}; /* {e['name']} */ \\")
    lines[-1] = lines[-1].rstrip(" \\")
    lines.append("")
    lines.append("// ---- target_zoom_int (auto_zoom.v) — integer shift amount for snap ----")
    lines.append("`define POI_ZOOM_INT_CASES \\")
    for e in encoded:
        zint = max(0, min(31, int(round(e['zoom_x10'] / 10.0))))
        lines.append(f"    {idx_bits}'d{e['idx']:<3}: target_zoom_int = 5'd{zint}; /* {e['name']} */ \\")
    lines[-1] = lines[-1].rstrip(" \\")
    lines.append("")
    lines.append("// ---- target_name_full (text_overlay.v) — 20-char overlay label ----")
    lines.append("`define POI_NAME_CASES \\")
    for e in encoded:
        lines.append(f"    {idx_bits}'d{e['idx']:<3}: target_name_full = \"{e['overlay']}\"; /* {e['name']} */ \\")
    lines[-1] = lines[-1].rstrip(" \\")

    with open(OUT_VH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nWrote {OUT_VH} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
